spring:
  datasource:
    url: jdbc:mysql://loacalhost:3306/librarymanagement
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
        show-sql: true

jwt:
  secret: 3df7#9kd^X@pL!m4Vr8eWzq1TbRuYc6FjK2HpLo9SaBvNmXt
  expiration: 3600000

